### PR TITLE
Added onClick Listener to CollectionDetails

### LINKED ISSUE #53: Add on Click listener to Collections RV
### Description

Add on Click listener to Collections RV to display the data contained in the collection

### PR DESCRIPTION
**Pull request by epicadk**
### Description

fixes #53
### Changes Done

Please ensure the following and put a check accordingly

- [x] My code doesn't break/affect any unrelated part of the codebase. 

- [x] Ran `./gradlew checkstyle` 

- [x] Squashed multiple commits (_if irrelevant_) into one commit

### CODE REVIEW

**Comment by epicadk** [comment]
unable to run gradlew checkstyle on windows

**Comment by devansh-299** [comment]
> 
> 
> unable to run gradlew checkstyle on windows

For windows, you need to use this command `gradlew checkstyle`

**Comment by epicadk** [comment]
> > unable to run gradlew checkstyle on windows
> 
> For windows, you need to use this command `gradlew checkstyle`

Yeah I tried that still doesn't work idk why.

**Comment by epicadk** [comment]
> > > unable to run gradlew checkstyle on windows
> > 
> > 
> > For windows, you need to use this command `gradlew checkstyle`
> 
> Yeah I tried that still doesn't work idk why.

@devansh-299 can you merge this?

**Review by devansh-299 — APPROVED** [review]
Nice work @epicadk !

**Pull request merged**
